title: ReadTheBlog
author: Timothée Mazzucotelli
email: timothee.mazzucotelli@pm.me
description: Findings, thoughts, tutorials, work. Pieces of my mind!

show_excerpts: true

github_username: pawamoy

disqus:
  shortname: pawamoy

rss: rss

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.html

# Build settings
markdown: kramdown
remote_theme: pawamoy/jekyll-readthedocs
permalink: pretty
plugins:
  - jekyll-feed
  - jemoji

highlight_theme: tomorrow

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
