title: ReadTheBlog
author: Timothée Mazzucotelli
email: timothee.mazzucotelli@gmail.com
description: Findings, thoughts, tutorials, work. Pieces of my mind!

social_sites:
  github: Pawamoy
  #twitter: jekyllrb
  #dribbble: jekyll
  #facebook: jekyll
  #flickr: jekyll
  #instagram: jekyll
  #linkedin: jekyll
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll

disqus:
  shortname: pawamoy

rss: rss

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
remote_theme: pawamoy/jekyll-readthedocs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
