# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pawablog -- Programming stuff
email: timothee.mazzucotelli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Just a blog about programming..."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pawamoy.github.io" # the base hostname & protocol for your site
github_username:  Pawamoy

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
